trigger:
  branches:
    include:
      - main

variables:
  imageName: 'spring-petclinic'
  acrLoginServer: 'sudhavetclinic01.azurecr.io'  # replace with your ACR login server

stages:
- stage: BuildAndPush
  displayName: 'Build, Analyze, and Push Docker Image to ACR'
  jobs:
  - job: Build
    displayName: 'CI Pipeline'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQubeServiceConnection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'spring-petclinic'
        cliProjectName: 'Spring PetClinic'
        extraProperties: |
          sonar.java.binaries=target/classes

    - script: mvn sonar:sonar
      displayName: 'Run SonarQube Analysis'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'azureconnection'  # Azure DevOps service connection to ACR
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)
