trigger:
  branches:
    include:
      - main

variables:
  imageName: 'spring-petclinic'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image to ACR'
  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image and Push to ACR'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azureconnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name sudhapetclinic01

          docker build -t sudhapetclinic01.azurecr.io/$(imageName):$(Build.BuildId) .
          docker push sudhapetclinic01.azurecr.io/$(imageName):$(Build.BuildId)
