trigger:
  branches:
    include:
      - main

variables:
  imageName: 'spring-petclinic'
  dockerRegistry: '<your-jfrog-registry-url>'     # e.g. sudha.jfrog.io
  dockerRepo: '<your-jfrog-repo>'                 # e.g. docker-local

stages:
- stage: BuildAndPush
  displayName: 'Build, Analyze, and Push Docker Image to JFrog'
  jobs:
  - job: Build
    displayName: 'Build and Push to JFrog'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true

    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQubeServiceConnection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'spring-petclinic'
        cliProjectName: 'Spring PetClinic'
        extraProperties: |
          sonar.java.binaries=target/classes

    - script: mvn sonar:sonar
      displayName: 'Run SonarQube Analysis'

    - task: Docker@2
      inputs:
        containerRegistry: 'JFrogDockerConnection'  # Service connection to JFrog
        repository: '$(dockerRepo)/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)
